import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TopNav } from "@/components/nav/top-nav";

const outfit = Outfit({ variable: '--font-sans', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kubera",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={outfit.variable}>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TopNav />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
